[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-stomp/stomp"
  version = "2.0.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"
